version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cajaclara
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"


volumes:
  postgres-data:
