"""update_default_user_password

Revision ID: 0823326d1ba6
Revises: d6a0b352b02f
Create Date: 2025-10-29 03:34:06.812124

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0823326d1ba6'
down_revision: Union[str, Sequence[str], None] = 'd6a0b352b02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update default user password from placeholder to hashed password
    op.execute("""
        UPDATE users
        SET hashed_password = '$2b$12$L17HGxDn4YC6v0MQizMKXeZvaUHmaEdKi3JNCTYMzIDYPHYbKzJ7G'
        WHERE id = '00000000-0000-0000-0000-000000000001'
        AND hashed_password = 'not-used-in-mvp'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
