"""add_bank_account_id_to_transactions

Revision ID: 5694fe6ce8ca
Revises: 2a2daffb847e
Create Date: 2025-10-30 00:27:01.087348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5694fe6ce8ca'
down_revision: Union[str, Sequence[str], None] = '2a2daffb847e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'user_id',
               existing_type=sa.UUID(),
               comment='ID del usuario propietario de la cuenta',
               existing_comment='Usuario propietario de la cuenta',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre de la cuenta bancaria',
               existing_comment='Nombre visible de la cuenta',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'color',
               existing_type=sa.VARCHAR(length=7),
               comment='Color en formato hexadecimal (#RRGGBB)',
               existing_comment='Color hexadecimal asignado a la cuenta',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'initial_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               comment='Saldo inicial de la cuenta',
               existing_comment='Saldo inicial registrado al crear la cuenta',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'current_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_comment='Saldo actual de la cuenta',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('uq_bank_accounts_user_name'), 'bank_accounts', type_='unique')
    op.create_table_comment(
        'bank_accounts',
        'Cuentas bancarias de los usuarios',
        existing_comment='Cuentas bancarias administradas por el usuario',
        schema=None
    )
    op.add_column('transactions', sa.Column('bank_account_id', sa.UUID(), nullable=True, comment='Cuenta bancaria asociada'))
    op.create_foreign_key(None, 'transactions', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'bank_account_id')
    op.create_table_comment(
        'bank_accounts',
        'Cuentas bancarias administradas por el usuario',
        existing_comment='Cuentas bancarias de los usuarios',
        schema=None
    )
    op.create_unique_constraint(op.f('uq_bank_accounts_user_name'), 'bank_accounts', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('bank_accounts', 'current_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_comment='Saldo actual de la cuenta',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bank_accounts', 'initial_balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               comment='Saldo inicial registrado al crear la cuenta',
               existing_comment='Saldo inicial de la cuenta',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'color',
               existing_type=sa.VARCHAR(length=7),
               comment='Color hexadecimal asignado a la cuenta',
               existing_comment='Color en formato hexadecimal (#RRGGBB)',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre visible de la cuenta',
               existing_comment='Nombre de la cuenta bancaria',
               existing_nullable=False)
    op.alter_column('bank_accounts', 'user_id',
               existing_type=sa.UUID(),
               comment='Usuario propietario de la cuenta',
               existing_comment='ID del usuario propietario de la cuenta',
               existing_nullable=False)
    # ### end Alembic commands ###
