"""add_transfer_account_fields

Revision ID: fb439fa9769c
Revises: 0823326d1ba6
Create Date: 2025-10-29 04:19:01.672732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb439fa9769c'
down_revision: Union[str, Sequence[str], None] = '0823326d1ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('from_account', sa.String(length=50), nullable=True, comment='Cuenta de origen (para transferencias)'))
    op.add_column('transactions', sa.Column('to_account', sa.String(length=50), nullable=True, comment='Cuenta de destino (para transferencias)'))
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Tipo: income, expense o transfer',
               existing_comment='Tipo: income o expense',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Tipo: income o expense',
               existing_comment='Tipo: income, expense o transfer',
               existing_nullable=False)
    op.drop_column('transactions', 'to_account')
    op.drop_column('transactions', 'from_account')
    # ### end Alembic commands ###
